server:
  port: 4010

spring:
  redis:
    host: 101.43.140.223
    port: 6379
    password: luowei...
    database: 0
    lettuce:
      pool:
        max-active: 20
        min-idle: 0
        max-wait: -1