server:
  port: 5000
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: oss
          uri: lb://my-club-oss
          predicates:
            - Path=/oss/**
          filters:
            - StripPrefix=1
        - id: subject
          uri: lb://my-club-subject
          predicates:
            - Path=/subject/**
          filters:
            - StripPrefix=1
        - id: auth
          uri: lb://my-club-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

  redis:
    host: 101.43.140.223
    port: 6379
    password: luowei...
    database: 0
    lettuce:
      pool:
        max-active: 20
        min-idle: 0
        max-wait: -1
